routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

Route::get('/', function () {
    // return view('admin.createProposal');
    return view('home');
});

Route::get('api/service', 'ServiceController@listOfServices');
Route::get('api/services/{catid}', 'ServiceController@servicesByCategory');
Route::get('api/categories', 'CategoryController@listOfServices');
Route::get('api/services/package/{id}', 'ServiceController@servicesByPackageId')->name('packageById');
Route::get('api/packages', 'PackageController@packages')->name('apiPackages');
Route::get('api/suppliers', 'SupplierController@listOfSuppliers');
Route::get('api/materials', 'MaterialController@listOfMaterials');

Route::get('api/materialsorders/destroy/{id}', 'MaterialsOrdersController@destroyAjax');

Route::resource('service', 'ServiceController');
Route::get('api/services/materials/{id}', 'ServiceController@materialsByServiceId')->name('materialsByServiceId');

Route::resource('category', 'CategoryController');

Route::resource('division', 'DivisionController' );

Route::resource('package', 'PackageController' );

Route::resource('material', 'MaterialController' );

Route::resource('supplier', 'SupplierController' );

Route::get('order/export/{id}', 'OrderController@exportOrderById')->name('exportorderbyid');
Route::get('order/export', 'OrderController@exportOrder');
Route::resource('order', 'OrderController' );
Route::get('api/order/createorder/{id}', 'OrderController@createOrderFromProposal');


Route::resource('proposal', 'ProposalController' );
Route::post('api/proposal/saveAjax','ProposalController@postProposalAjax');
Route::post('api/proposal/updateAjax','ProposalController@updateProposalAjax');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/createProposal.blade.php
@extends('layouts.app')
@section('title', 'Criar Orçamento')

@section('content')
@include('layouts.modalServices')
@include('layouts.modalCategories')
@include('layouts.modalPackages')
<?php //dd($iva); ?>
<?php //dd($proposal); ?>
<div class="card">
  <div class="card-header">
    @if(isset($proposal))
    <a class="btn btn-primary pull-right" href="{{ route('proposal.show', ['proposal' => $proposal->id]) }}">Ver Orçamento <i class="fas fa-file-alt"></i></a>
    @endif

    @if(isset($order))
    <a class="btn btn-primary pull-right" href="{{ route('order.edit', ['order' => $order->id]) }}">Ver Encomenda <i class="fas fa-file-alt"></i></a>
    @elseif(isset($proposal))
    <a class="btn btn-primary pull-right" id="create_order_btn" href="javascript:;">+ Criar Encomenda <i class="fas fa-file-alt"></i></a>
    @endif
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-6">
        <div id="client-data" class="card">
          <div class="card-header">Cliente</div>
          <div class="card-body">
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->name) ? $proposal->name : ''}}" name="name" type="text" placeholder="Nome" autocomplete="false" required>
            </div>
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->address) ? $proposal->address : ''}}" name="address" type="text" placeholder="Morada" autocomplete="false">
            </div>
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->phone) ? $proposal->phone : ''}}" name="phone" type="text" placeholder="Telefone" autocomplete="false">
            </div>
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->obra) ? $proposal->obra : ''}}" name="obra" type="text" placeholder="Obra" autocomplete="false">
            </div>
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->gestor) ? $proposal->gestor : ''}}" name="gestor" type="text" placeholder="Gestor" autocomplete="false">
            </div>
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->prazo) ? $proposal->prazo : ''}}" name="prazo" type="text" placeholder="Prazo" autocomplete="false">
            </div>
            <div class="form-group">
              <input class="form-control" value="{{isset($proposal->email) ? $proposal->email : ''}}" name="email" type="text" placeholder="Email" autocomplete="false">
            </div>



            <div class="form-group">
              <label for="status">Status</label>
              <select type="text" name="status" class="form-control" id="status">
                    <option {{(isset($proposal) && $proposal->status == "Rascunho") ? 'selected' : ''}} value="Rascunho">Rascunho</option>
                    <option {{(isset($proposal) && $proposal->status == "Em Espera") ? 'selected' : ''}} value="Em Espera">Em Espera</option>
                    <option {{(isset($proposal) && $proposal->status == "Espera Revisão Valores") ? 'selected' : ''}} value="Espera Revisão Valores">Espera Revisão Valores</option>
                    <option {{(isset($proposal) && $proposal->status == "Enviado") ? 'selected' : ''}} value="Enviado">Enviado</option>
                    <option {{(isset($proposal) && $proposal->status == "Em andamento") ? 'selected' : ''}} value="Em andamento">Em andamento</option>
                    <option {{(isset($proposal) && $proposal->status == "Adjudicado") ? 'selected' : ''}} value="Adjudicado">Adjudicado</option>
                    <option {{(isset($proposal) && $proposal->status == "Fechado") ? 'selected' : ''}} value="Fechado">Fechado</option>
                </select>
            </div>

            <div class="form-group">
                <label for="general_iva">IVA</label>
                <select type="text" name="general_iva" class="form-control" id="general_iva" aria-describedby="titleHelp">
                    @foreach($ivas as $iva)
                    <option {{(isset($iva) && isset($proposal) && $iva->id == $proposal->iva_id) ? 'selected' : ''}} value="{{$iva->id}}">{{$iva->title}}</option>
                    @endforeach
                </select>
                <small id="categoryHelp" class="form-text text-muted">Taxa de IVA</small>

            </div>

          </div>
        </div>
        <hr>

        @if(!isset($services) || count($services) == 0)
        <div class="card" id="create-division">
          <div class="card-header">Configuração da moradia</div>
          <div class="card-body">
            <div class="form-group">
              <label for="tipologia">Tipologia</label>
              <select class="form-control" id="tipologia">
                <option value="0">T0</option>
                <option value="1">T1</option>
                <option value="2">T2</option>
                <option value="3">T3</option>
                <option value="4">T4</option>
                <option value="5">T5</option>
              </select>
              <small class="form-text text-muted">Escolha a tipologia do imóvel</small>
            </div>
            <!-- <div class="form-group">
          <label for="area">Área (m2)</label>
          <input class="form-control" type="text" placeholder="Insira a área em M2">
      </div> -->
            <div class="form-group">
              <label for="wcs">Casas de banho</label>
              <select class="form-control" id="wcs">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>
              <small class="form-text text-muted">Escolha o número de casas de banho</small>
            </div>
            <div class="form-group form-check">
              <input type="checkbox" class="form-check-input" id="with-hall">
              <label class="form-check-label" for="with-hall">Hall de entrada?</label>
            </div>
            <button class="btn btn-primary" id="btnCreateDivisions">Criar divisões</button>
          </div>

        </div>
        @endif

      </div>
      <div class="col">
        <div id="add-extras-data" class="card">
          <div class="card-header">+</div>
          <div class="card-body">
            <div class="form-group">
              <input class="form-control" name="division-name" id="division-name" type="text" placeholder="Nome da divisão" autocomplete="nope">
            </div>
            <div class="form-group">

              <button id="btn-add-tab" type="button" class="btn btn-primary pull-right">Adicionar divisão</button>
            </div>

            <div class="form-group">

            <label for="notes">Notas</label>
              <textarea class="form-control" rows="5" name="notes" id="notes" autocomplete="nope">{{isset($proposal->notes) ? $proposal->notes : ''}}</textarea>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist"></div>
    </nav>
    <div class="tab-content" id="nav-tabContent"></div>
  </div>

</div>


<div id="hidde-contents" style="display:none">
  <div class="form-group" id="input-div">
    <input class="form-control" name="name" type="text" id="input-field">
  </div>
</div>


@csrf

@if(isset($services))
<input type="hidden" name="proposal_id" value="{{$proposal->id}}" />

<div class="col align-center" id="loading-tabs-jobs">
  <i class="fas fa-spinner fa-spin fa-4x"></i>
</div>
@endif

@push('scripts')
<script src="/admin/js/scripts.js?v=23112021_16172"></script>
@endpush

@section('footer-scripts')
@if(isset($services))
<script>

  @if(isset($proposal->tabs))
    @foreach($proposal->tabs as $tab)
    createTabs('{{str_replace("tab-", "", $tab->tab_id)}}', '{{$tab->title}}', '{{$tab->id}}', @json($tab));
    @endforeach
  @endif
  //$('#create-division').hide();

  // @foreach($divisions as $division)
  // //createTabs('{{str_replace("tab-", "", $division->tabid)}}', '{{$division->tab_name}}', '');
  // createTabs('{{str_replace("tab-", "", $division->tabid)}}', '{{$division->tab_name}}', '');
  // @endforeach

  @if(isset($services))
  @foreach($services as $service)

  addLiJob('{{$service->tabid}}', @json($service), true);
  @endforeach
  @endif

  $('#loading-tabs-jobs').hide();
</script>
@endif
@endsection

@endsection

resources/views/admin/exportOrder.blade.php
<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Título</th>
            <th>Fornecedor</th>
            <th>Status</th>
            <th>Produto</th>
            <th>Divisão</th>
            <th>Serviço</th>
            <th>Categoria</th>
            <th>Un.</th>
            <th>Qt.</th>
            <th>Preço</th>
            <th>Subtotal</th>
            <th>Data Entrega</th>
            <th>Qt. Final</th>
            <th>Preço final</th>
            <th>Subtotal Final</th>
        </tr>
    </thead>
    <tbody>

        @foreach ($orders->materials->load('proposalService') as $order)
            <?php
            $service = DB::table('proposal_services')
                ->where('id', '=', $order->service_id)
                ->first();
            $status_order = null;
            foreach ($status_list as $status) {
                if ($status->id === $order->status) {
                    $status_order = $status->title;
                }
            }
            ?>
            <tr>
                <td>{{ $order->id }}</td>
                <td>{{ $order->title }}</td>
                <td>{{ $order->supplier_title }}</td>
                <td>{{ $status_order }}</td>
                <td>{{ $order->description }}</td>
                <td>{{ $order->tab_name }}</td>
                <td>{{ isset($service->title) ? $service->title : '' }}</td>
                <td>{{ $order->category_title }}</td>
                <td>{{ $order->unit }}</td>
                <td>{{ $order->quantity }}</td>
                <td>{{ $order->price }}</td>
                <td>{{ $order->subtotal }}</td>
                <td>{{ $order->delivery_date }}</td>
                <td>{{ $order->final_quantity }}</td>
                <td>{{ $order->final_price }}</td>
                <td>{{ $order->final_subtotal }}</td>
            </tr>

        @endforeach


    </tbody>

</table>

resources/views/admin/formCategory.blade.php
@extends('layouts.app')

@section('title', 'Criar Categoria')

@section('content')

<div class="card">
    <div class="card-body">
        <form action="{{isset($category->id) ? route('category.update', $category) : route('category.store')}}" method="post">
            @if(isset($category))
            @method('put')
            <input type="hidden" value="{{$category->id}}" name="id" />
            @endif
            @csrf

            <div class="form-group">
                <label for="title">Nome</label>
                <input type="text" value="{{isset($category->title) ? $category->title : ''}}" name="title" class="form-control" id="title" aria-describedby="titleHelp">
                <small id="titleHelp" class="form-text text-muted">Nome do serviço</small>
            </div>
            <div class="form-group">
                <label for="description">Descrição</label>
                <textarea name="description" class="form-control" id="description" aria-describedby="descriptionHelp">{{isset($category->description) ? $category->description : ''}}</textarea>
                <small id="descriptionHelp" class="form-text text-muted">Descrição do serviço</small>
            </div>

            <button type="submit" class="btn btn-primary">Salvar</button>

        </form>
    </div>
</div>

@endsection

resources/views/admin/formPackage.blade.php
@extends('layouts.app')

@section('title', 'Criar/Editar Pack')

@section('content')
@include('layouts.modalServices')

<div class="card">
    <div class="card-body">
        <form action="{{isset($package->id) ? route('package.update', $package) : route('package.store')}}" method="post">
            @if(isset($package->id))
            @method('put')
            <input type="hidden" value="{{$package->id}}" name="id" />            
            @endif
            @csrf

            <input type="hidden" name="selections"/>

            <div class="form-group">
                <label for="title">Nome</label>
                <input type="text" value="{{isset($package->title) ? $package->title : ''}}" name="title" class="form-control" id="title" aria-describedby="titleHelp">
                <small id="titleHelp" class="form-text text-muted">Nome do serviço</small>
            </div>
            <div class="form-group">
                <label for="description">Descrição</label>
                <textarea name="description" class="form-control" id="description" aria-describedby="descriptionHelp">{{isset($package->description) ? $package->description : ''}}</textarea>
                <small id="descriptionHelp" class="form-text text-muted">Descrição do serviço</small>
            </div>
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalTable">Adicionar trabalhos</button>
            <button type="submit" id="save" class="btn btn-primary">Salvar</button>

        </form>

        <!-- <div id="toolbar">
            <button id="btnRemove" class="btn btn-secondary">Remover</button>
        </div> -->
        <table id="tableServicesPack" 
        data-toggle="table" 
        data-height="400" 
        data-width="600" 
        data-pagination="true" 
        data-search="true" 
        data-buttons="buttons"
        data-use-row-attr-func="true"
        data-reorderable-rows="true"
        data-url="{{isset($package->id) ? route('packageById', ['id' => $package->id]) : ''}}">
            <thead>
                <tr>
                    <th data-field="state" data-checkbox="true"></th>
                    <th data-field="id">ID</th>
                    <th data-field="title">Nome</th>
                    <th data-field="cat_name">Categoria</th>
                    <th data-field="unit">Unidade</th>
                    <th data-field="price">Preço</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@push('scripts')
<script>
    var $servicesTable = $('#tableInModal');
    var $servicesInPackTable = $('#tableServicesPack');

    function buttons() {
        return {
            btnRemoveEvenRows: {
                'text': 'Remover',
                'icon': 'fa-trash',
                'event': () => {
                    removeSelections()
                },
                'attributes': {
                    'title': 'Remover selecionados'
                }
            }
        }
    }

    $servicesTable.bootstrapTable({
        onClickRow: function(row, e) {
            $('#tableServicesPack').bootstrapTable('append', row);
            console.log(row, e);
        }
    });

    function removeSelections() {
        var ids = $.map($servicesInPackTable.bootstrapTable('getSelections'), function(row) {
            return row.id
        });

        $servicesInPackTable.bootstrapTable('remove', {
            field: 'id',
            values: ids
        })
    }

    $(document).on('click', '#save', function(e) {
        var selections = $('#tableServicesPack').bootstrapTable('getData');
        selections = selections.map(s => s.id);
        //selections = JSON.stringify(selections)
        $('input[name=selections]').val(selections);
    })
</script>
@endpush

@endsection

resources/views/admin/listCategories.blade.php
@extends('layouts.app')

@section('title', 'Serviços')

@section('content')
<div class="card">
    <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/category/create" class="btn btn-primary">+ Adicionar</a>
    </nav>
    <table data-toggle="table"
    data-search="true"
    data-show-columns="true"
    data-pagination="true">
    <thead>
        <tr>
            <th>id</th>
            <th>Título</th>
            <th>Descrição</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach ($categories as $category)
        <tr>
            <td>{{ $category->id }}</td>
            <td>{{ $category->title }}</td>
            <td>{{ $category->description }}</td>
            <td>
            <a class="btn btn-primary" href="{{ route('category.edit', ['category' => $category->id]) }}"><i class="fas fa-edit"></i></a> Editar
            
            
            <form action="{{ route('category.destroy', $category->id) }}" method="POST" style="float:right">

              @csrf
              @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

            </td>

        </tr>
        @endforeach
    </tbody>
</table>

    </div>
</div>

@endsection

resources/views/admin/listMaterials.blade.php
@extends('layouts.app')

@section('title', 'Materiais')

@section('content')
<div class="card">
  <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/material/create" class="btn btn-primary">+ Adicionar</a>
    </nav>

    <table data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
      <thead>
        <tr>
          <th>ID</th>
          <th>Título</th>
          <th>Fornecedor</th>
          <th>Serviços</th>
          <th>Preço</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        @foreach ($materials as $material)
        <?php
        $services = DB::table('services_materials')
          ->leftJoin('services', 'services.id', '=', 'services_materials.service_id')
          ->select('services.id', 'services.title')
          ->where('material_id', '=', $material->id)
          ->get();
        ?>
        <tr>
          <td>{{ $material->id }}</td>
          <td>{{ $material->title }}</td>
          <td>{{ $material->supplier_title }}</td>
          <td>
            @foreach($services as $service)
            <ul>
                @if(isset($service->id))
              <li><a href="{{route('service.edit', ['service' => $service->id])}}" target="_blank">{{$service->title}}</a></li>
              @endif
            </ul>
            @endforeach
          </td>
          <td>{{ $material->unit_price }}</td>
          <td>
            <a class="btn btn-primary" href="{{ route('material.edit', ['material' => $material->id]) }}"><i class="fas fa-edit"></i> Editar</a>

            <form action="{{ route('material.destroy', $material->id) }}" method="POST" style="float:right">

              @csrf
              @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

          </td>

        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/admin/listOrders.blade.php
@extends('layouts.app')

@section('title', 'Encomendas')

@section('content')

<div class="card">
  <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/order/create" class="btn btn-primary">+ Adicionar</a>
    </nav>

    <table data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
      <thead>
        <tr>
          <th>Título</th>
          <th>Descrição</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        @foreach ($orders as $order)
        <tr>
          <td>{{ $order->title }}</td>
          <td>{{ $order->description }}</td>
          <td>
            <a class="btn btn-primary" href="{{ route('order.edit', ['order' => $order->id]) }}"><i class="fas fa-edit"></i> Editar</a>

            <form action="{{ route('order.destroy', $order->id) }}" method="POST" style="float:right">

              @csrf
              @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

          </td>

        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/admin/listPackages.blade.php
@extends('layouts.app')

@section('title', 'Serviços')

@section('content')
<?php //phpinfo(); ?>
<div class="card">
  <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/package/create" class="btn btn-primary">+ Adicionar</a>
    </nav>

    <table data-toggle="table"
    data-search="true"
    data-show-columns="true"
    data-pagination="true">
      <thead>
        <tr>
          <th>Título</th>
          <th>Descrição</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        @foreach ($packages as $package)
        <tr>
          <td>{{ $package->title }}</td>
          <td>{{ $package->description }}</td>
          <td>
          <a class="btn btn-primary" href="{{ route('package.edit', ['package' => $package->id]) }}"><i class="fas fa-edit"></i> Editar</a>
          
          <form action="{{ route('package.destroy', $package->id) }}" method="POST" style="float:right">

              @csrf
              @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

          </td>


        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/admin/listProposals.blade.php
@extends('layouts.app')

@section('title', 'Orçamentos')

@section('content')

<div class="card">
  <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/proposal/create" class="btn btn-primary">+ Adicionar</a>
    </nav>

    <table data-toggle="table"
    data-search="true"
    data-show-columns="true"
    data-pagination="true">
      <thead>
        <tr>
          <th>#</th>          
          <th>Nome</th>
          <th>Telefone</th>
          <th>Status</th>
          <th>ID Orçamento</th>
          <th></th>
          
        </tr>
      </thead>
      <tbody>

        @foreach ($proposals as $proposal)
        <tr>
          <td>{{ $proposal->id }}</td>
          <td>{{ $proposal->name }}</td>
          <td>{{ $proposal->phone }}</td>
          <td>{{ $proposal->status }}</td>
          <td>ORC-00{{$proposal->id+110}}-{{date('Y', strtotime($proposal->created_at))}}</td>
          <td>
            <a class="btn btn-primary" href="{{ route('proposal.edit', ['proposal' => $proposal->id]) }}"><i class="fas fa-edit fa-lg"></i> Editar</a> 
            <a class="btn btn-primary" href="{{ route('proposal.show', ['proposal' => $proposal->id]) }}"><i class="fas fa-file-alt fa-lg"></i> Ver</a>             

            <form action="{{ route('proposal.destroy', $proposal->id) }}" method="POST" style="float:right" >   

                @csrf
                @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

          </td>
          

        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/admin/listServices.blade.php
@extends('layouts.app')

@section('title', 'Serviços')

@section('content')

<div class="card">
  <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/service/create" class="btn btn-primary">+ Adicionar</a>
    </nav>

    <table data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
      <thead>
        <tr>
          <th>Título</th>
          <th>Categoria</th>
          <th>Descrição</th>
          <th>Preço</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        @foreach ($services as $service)
        <tr>
          <td>{{ $service->title }}</td>
          <td>{{ $service->cat_name }}</td>
          <td>{{ $service->description }}</td>
          <td>{{ $service->price }}</td>
          <td>
            <a class="btn btn-primary" href="{{ route('service.edit', ['service' => $service->id]) }}"><i class="fas fa-edit"></i> Editar</a>

            <form action="{{ route('service.destroy', $service->id) }}" method="POST" style="float:right">

              @csrf
              @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

          </td>

        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/admin/listSuppliers.blade.php
@extends('layouts.app')

@section('title', 'Fornecedores')

@section('content')

<div class="card">
  <div class="card-body">
    <nav class="navbar navbar-light bg-light">
      <a href="/supplier/create" class="btn btn-primary">+ Adicionar</a>
    </nav>

    <table data-toggle="table" data-search="true" data-show-columns="true" data-pagination="true">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Telefone</th>
          <th></th>
        </tr>
      </thead>
      <tbody>

        @foreach ($suppliers as $supplier)
        <tr>
          <td>{{ $supplier->title }}</td>
          <td>{{ $supplier->phone }}</td>
          <td>
            <a class="btn btn-primary" href="{{ route('supplier.edit', ['supplier' => $supplier->id]) }}"><i class="fas fa-edit"></i> Editar</a>

            <form action="{{ route('supplier.destroy', $supplier->id) }}" method="POST" style="float:right">

              @csrf
              @method('DELETE')

              <button type="submit" class="btn btn-danger" onclick="return confirm('Quer mesmo apagar?')"><i class="fas fa-trash fa-lg"></i> Apagar</button>
            </form>

          </td>

        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

@endsection

resources/views/admin/proposal.blade.php
@extends('layouts.app')

@section('title', 'Page Title')

@section('content')
<script>
  window.dataServices = '{{ $servicesJson }}';
</script>

<form>
    <div class="form-group">
        <select class="form-control" id="tipologia">
            <option>Tipologia</option>
            <option value="1">T1</option>
            <option value="2">T2</option>
            <option value="3">T3</option>
            <option value="4">T4</option>
            <option value="5">T5</option>
        </select>
        <small class="form-text text-muted">Escolha a tipologia do imóvel</small>
    </div>
    <div class="form-group">
        <label for="area">Área (m2)</label>
        <input class="form-control" type="text" placeholder="Insira a área em M2">
    </div>
    <div class="form-group">
        <select class="form-control" id="wcs">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
        </select>
        <small class="form-text text-muted">Número de casas de banho</small>
    </div>
    <button class="btn btn-primary" id="btnCreateDivisions">Criar divisões</button>
</form>
<br>
<br>
<div class="container">
    <p>
        <button id="btn-add-tab" type="button" class="btn btn-primary pull-right">Adicionar divisão</button>
    </p> 
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist"></div>
    </nav>
    <div class="tab-content" id="nav-tabContent"></div>
</div>
<script>
    
</script>
@endsection